---
title: "Encuadre"
---

## Fines del aprendizaje o formación

Distinguir los procesos de fabricación, ensamble y acabados de los diversos materiales y piezas empleadas en máquinas, equipos y sistemas mecatrónicos para garantizar su calidad, eficiencia, productibilidad y rentabilidad.

## Contenido temático

UNIDAD I. Proceso de obtención del hierro y el acero.

1. Proceso tecnológico del hierro de primera fusión.
2. Funcionamiento del proceso tecnológico y otros productos obtenidos.
3. Afino del acero.
4. Procesos tecnológicos para la obtención del acero, hornos BOF, eléctricos, convertidores Bessemer y Thomas.

UNIDAD II. Tratamiento térmico del acero.

1. Generalidades.
2. Clasificación de los tratamientos térmicos.
3. Recocido.
4. Temple.
5. Revenido.
6. Tratamientos termoquímicos.

UNIDAD III. Proceso de cambio de forma.

1. Fundición, colado al alto vacío, centrífuga y precisión.
2. Formado mecánico, forjado, prensado, estirado, cizallado, doblado, extrusión, embutido y troquelado.
3. Desprendimiento de viruta por maquinado, convencional y CNC.

UNIDAD IV. Procesos industriales de plásticos térmicos, compuestos y termofraguantes, y materiales cerámicos.

1. Generalidades.
2. Tipos de plásticos.
3. Materias primas.
4. Compuestos termofraguantes (fenólicas, resinosas y furámicas).
5. Celulosas, poliestirenos, polietilenos y propilenos.
6. Materiales cerámicos.

UNIDAD V. Procesos de manufactura especiales de empresas regionales.

1. Maquinados con chorro abrasivo.
2. Maquinados con chorro de agua.
3. Procesos de ensamble (no permanentes, semipermanentes y permanentes).
4. Procesos regionales.

## Criterios de Evaluación.

Criterio | Ponderación
:---|---:
Reportes de lectura | 10%
Exposición temática o de trabajos | 10%
Participación en clase | 5%
Reportes escritos de observaciones e información recopilada | 5%
Esquemas | 10%
Exámenes | 60%
_TOTAL_ | 100%
